<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tickiting Application</title>
    <!-- Bootstrap core CSS -->
    <link href="../../../../css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1>Ooooops!</h1>

                <p><b>Message: </b> <?=$exception->getMessage();?></p>
                <p>On line <?=$exception->getLine();?> in <?=$exception->getFile();?></p>
            </div>
        </div>
    </div>
</body>
</html>
