<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tickiting Application</title>
    <!-- Bootstrap core CSS -->
    <link href="../../../../css/bootstrap.min.css" rel="stylesheet">
    
</head>
<body>

<div class="container">
	<div class="row">
        <div class="col-md-4">
            <div class="form_main">
                <h4 class="heading"><strong>New Ticket</strong></h4>
                <div class="form">
                    <form method="post" action="<?=$router->pathFor('ticket-new') ?>">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input name="title" id="title" class="form-control" type="text" placeholder="Title" required />
                        </div>
                        <div class="form-group">
                            <label for="component">Component</label>
                            <select class="form-control" name="component" id="component" required>
                                <option value="">Select Component</option>
                                <?php
                                foreach($components as $component): ?>
                                    <option value="<?=$component->getId()?>"><?=$component->getName()?></option>
                                <?php
                                endforeach;
                                ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea name="description" required id="description" class="form-control" rows="3" placeholder="Description"></textarea>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
                    </form>
                </div>
            </div>
        </div
	</div>
</div>




<!-- <form class="pure-form" method="post" action="/ticket/new">
    <label for="title">Title</label>
    <input name="title" id="title" type="text" size="60" /><br />

    <label for="description">Description</label>
    <textarea name="description" id="description" rows="6" cols="80"></textarea><br />

    <label for="component">Component</label>
    <select name="component">
        <option value=""></option>
<?php
foreach($components as $component): ?>
    <option value="<?=$component->getId()?>"><?=$component->getName()?></option>
<?php
endforeach;
?>
    </select><br />

    <input type="submit" class="pure-button" value="Create" />
</form> -->

</body>
</html>


