<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tickiting Application</title>
    <!-- Bootstrap core CSS -->
    <link href="../../../../css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="panel panel-primary">
                    <h4 class="heading"><strong>View Ticket</strong></h4>
                    <p><a href="<?=$router->pathFor('ticket-new') ?>">Add new ticket</a></p>
                    <table class="table table-bordered">
                        <tbody>
                            <tr><td>Title</td><td><?=$ticket->getTitle()?></td></tr>
                            <tr><td>Component</td><td><?=$ticket->getComponent()?></td></tr>
                            <tr><td>Description</td><td><?=$ticket->getDescription()?></td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>



